blobby: blobby.c
	dcc blobby.c -o blobby

.PHONY: clean
clean:
	rm blobby

.PHONY: test
test:
	1521 autotest blobby blobby.c

.PHONY: 0
0:
	1521 autotest blobby subset0 blobby.c

.PHONY: 1
1:
	1521 autotest blobby subset1 blobby.c

.PHONY: 2
2:
	1521 autotest blobby subset2 blobby.c

.PHONY: 3
3:
	1521 autotest blobby subset3 blobby.c

.PHONY: 4
4:
	1521 autotest blobby subset4 blobby.c
